import type { LevelMeta, Unit } from "@/types/curriculum";
import { LESSON_META } from "@/data/lessons/meta";

/**
 * ═══════════════════════════════════════════════════════════
 *  المنهج الأكاديمي الكامل — مصدر البيانات الوحيد للمسار التعليمي
 *  (فصل تام بين المحتوى والمكونات كما هو مطلوب)
 * ═══════════════════════════════════════════════════════════
 *  4 مستويات (A1→B2) × 46 وحدة دراسية (وحدات عرض) تغطي 48 درساً فعلياً
 */

export const LEVELS: LevelMeta[] = [
  {
    code: "A1",
    titleDe: "Anfänger",
    subtitleDe: "Grundstufe 1",
    titleAr: "المبتدئ",
    description:
      "نقطة الانطلاق: الأبجدية والنطق، التعارف، الضمائر والأفعال في المضارع، أدوات التعريف والتنكير، الأرقام والوقت، وبناء أول جمل صحيحة بالترتيب الألماني (الفعل في المركز الثاني).",
    topics: ["Präsens", "Nominativ / Akkusativ", "W-Fragen", "Zahlen & Uhrzeit", "Imperativ", "kein / nicht"],
    units: 13,
    words: 800,
    unlockThreshold: 80,
    gradient: "from-sky-500 via-blue-500 to-indigo-500",
    accent: "#0ea5e9",
    emoji: "🌱",
  },
  {
    code: "A2",
    titleDe: "Grundstufe 2",
    subtitleDe: "Grundstufe 2",
    titleAr: "ما قبل المتوسط",
    description:
      "التوسع في الزمن الماضي (Perfekt/Präteritum)، حالة الجر (Dativ)، الأفعال الشرطية الست، حروف الجر المتغيرة، الجمل الثانوية الأولى (weil/dass/wenn)، والمقارنة والتفضيل.",
    topics: ["Perfekt", "Präteritum", "Dativ", "Modalverben", "Wechselpräpositionen", "weil / dass / wenn"],
    units: 12,
    words: 800,
    unlockThreshold: 80,
    gradient: "from-emerald-500 via-teal-500 to-cyan-500",
    accent: "#10b981",
    emoji: "🌿",
  },
  {
    code: "B1",
    titleDe: "Mittelstufe 1",
    subtitleDe: "Mittelstufe 1",
    titleAr: "المتوسط",
    description:
      "المرحلة الفاصلة نحو الاستقلالية: الماضي التام، المضاف إليه (Genitiv)، الجمل الثانوية الكاملة، صيغة الشرط (Konjunktiv II)، المبني للمجهول، تصريف الصفات بالكامل، والمستقبل.",
    topics: ["Genitiv", "Nebensätze", "Konjunktiv II", "Passiv", "Adjektivdeklination", "Relativsätze", "Futur I"],
    units: 11,
    words: 1000,
    unlockThreshold: 80,
    gradient: "from-amber-500 via-orange-500 to-rose-500",
    accent: "#f59e0b",
    emoji: "🌳",
  },
  {
    code: "B2",
    titleDe: "Mittelstufe 2",
    subtitleDe: "Mittelstufe 2",
    titleAr: "المتقدم",
    description:
      "القمة: نقل الكلام غير المباشر (Konjunktiv I)، البناء للمجهول المتقدم، الاشتقاق الاسمي، الصفات المشتقة من الفعل، الروابط المتقدمة، والكتابة الأكاديمية والرسمية.",
    topics: ["Konjunktiv I", "Passiv fortgeschritten", "Nominalisierung", "Partizipialkonstruktionen", "Futur II", "Konnektoren"],
    units: 10,
    words: 1000,
    unlockThreshold: 80,
    gradient: "from-rose-500 via-pink-500 to-fuchsia-500",
    accent: "#f43f5e",
    emoji: "🌲",
  },
];

export const UNITS: Unit[] = [
  // ═══ A1 — 12 وحدة ═══
  {
    id: "a1-01",
    level: "A1",
    number: 1,
    titleDe: "Hallo! Ich heiße …",
    titleAr: "التعارف والتحيات",
    descDe: "Begrüßungen, das Alphabet und sich vorstellen.",
    descAr: "التحيات، الحروف الأبجدية والنطق، والتعريف بالنفس والآخرين.",
    lessons: 6,
    minutes: 55,
    keyWords: ["Hallo", "Guten Tag", "heißen", "kommen aus", "das Alphabet"],
  },
  {
    id: "a1-02",
    level: "A1",
    number: 2,
    titleDe: "Meine Familie",
    titleAr: "العائلة والأصدقاء",
    descDe: "Familienmitglieder vorstellen und Possessivartikel.",
    descAr: "أفراد العائلة، أدوات الملكية (mein/dein)، ووصف العلاقات.",
    lessons: 6,
    minutes: 55,
    keyWords: ["die Familie", "der Vater", "die Mutter", "mein", "dein"],
  },
  {
    id: "a1-03",
    level: "A1",
    number: 3,
    titleDe: "Essen und Trinken",
    titleAr: "الطعام والشراب",
    descDe: "Lebensmittel, der Akkusativ und einkaufen gehen.",
    descAr: "المأكولات والمشروبات، حالة النصب (Akkusativ) مع der/ein، والتسوق.",
    lessons: 6,
    minutes: 50,
    keyWords: ["das Brot", "der Apfel", "essen", "trinken", "der Akkusativ"],
  },
  {
    id: "a1-04",
    level: "A1",
    number: 4,
    titleDe: "Meine Wohnung",
    titleAr: "السكن والمنزل",
    descDe: "Die Wohnung beschreiben und über Möbel sprechen.",
    descAr: "وصف الشقة والمنزل، الأثاث، وحروف الجر مع المكان (in/auf).",
    lessons: 6,
    minutes: 50,
    keyWords: ["das Zimmer", "die Küche", "wohnen", "die Möbel", "in/auf"],
  },
  {
    id: "a1-05",
    level: "A1",
    number: 5,
    titleDe: "Mein Tag",
    titleAr: "الحياة اليومية والروتين",
    descDe: "Tagesablauf, Uhrzeiten und trennbare Verben.",
    descAr: "الروتين اليومي، الساعة وأوقات اليوم، والأفعال المنفصلة.",
    lessons: 6,
    minutes: 55,
    keyWords: ["aufstehen", "die Uhrzeit", "am Morgen", "trennbare Verben"],
  },
  {
    id: "a1-06",
    level: "A1",
    number: 6,
    titleDe: "Freizeit und Hobbys",
    titleAr: "أوقات الفراغ والهوايات",
    descDe: "Über Hobbys sprechen und Verabredungen treffen.",
    descAr: "الحديث عن الهوايات، صيغة الأمر (Imperativ)، وتنظيم المواعيد.",
    lessons: 6,
    minutes: 50,
    keyWords: ["das Hobby", "spielen", "der Sport", "der Imperativ"],
  },
  {
    id: "a1-07",
    level: "A1",
    number: 7,
    titleDe: "Einkaufen & Zahlen",
    titleAr: "التسوق والأرقام",
    descDe: "Einkaufen, Preise, Mengenangaben, Telefonnummern und Adressen.",
    descAr: "التسوق والأسعار والكميات، ثم درس الأرقام والهاتف والعناوين (a1-14): أرقام حتى 100 بثقة، أرقام الهاتف، والعناوين.",
    lessons: 2,
    minutes: 50,
    keyWords: ["der Preis", "kosten", "das Kilo", "die Telefonnummer", "die Adresse"],
  },
  {
    id: "a1-08",
    level: "A1",
    number: 8,
    titleDe: "Kleidung und Farben",
    titleAr: "الملابس والألوان",
    descDe: "Kleidung, Farben und Adjektive als Prädikat.",
    descAr: "الملابس والألوان، الصفات الخبرية، والسؤال عن الرأي (Wie findest du?).",
    lessons: 5,
    minutes: 45,
    keyWords: ["das Hemd", "die Farbe", "rot", "tragen", "finden"],
  },
  {
    id: "a1-09",
    level: "A1",
    number: 9,
    titleDe: "Termine und Uhrzeit",
    titleAr: "المواعيد والوقت",
    descDe: "Termine, Wochentage, Monate und Jahreszeiten.",
    descAr: "المواعيد، أيام الأسبوع، الأشهر والفصول، والأعداد الترتيبية.",
    lessons: 5,
    minutes: 45,
    keyWords: ["der Termin", "der Wochentag", "der Monat", "um/am"],
  },
  {
    id: "a1-10",
    level: "A1",
    number: 10,
    titleDe: "Arbeit und Berufe",
    titleAr: "العمل والمهن",
    descDe: "Berufe nennen und über die Arbeit sprechen.",
    descAr: "المهن والوظائف، النفي بـ (nicht/kein)، والحديث عن العمل.",
    lessons: 5,
    minutes: 45,
    keyWords: ["der Beruf", "arbeiten", "der Arzt", "nicht", "kein"],
  },
  {
    id: "a1-11",
    level: "A1",
    number: 11,
    titleDe: "In der Stadt",
    titleAr: "التنقل في المدينة",
    descDe: "Nach dem Weg fragen und Wegbeschreibungen verstehen.",
    descAr: "السؤال عن الطريق، الاتجاهات، ووسائل النقل الأساسية.",
    lessons: 5,
    minutes: 45,
    keyWords: ["die Straße", "geradeaus", "rechts", "links", "der Bahnhof"],
  },
  {
    id: "a1-12",
    level: "A1",
    number: 12,
    titleDe: "Wetter und Jahreszeiten",
    titleAr: "الطقس والفصول",
    descDe: "Über das Wetter sprechen und es ist + Adjektiv.",
    descAr: "الحديث عن الطقس، (es ist + صفة)، والملابس المناسبة لكل فصل.",
    lessons: 5,
    minutes: 45,
    keyWords: ["das Wetter", "die Sonne", "der Regen", "es ist kalt"],
  },
  {
    id: "a1-13",
    level: "A1",
    number: 13,
    titleDe: "A1 kompakt — die große Wiederholung",
    titleAr: "A1 المراجعة الشاملة",
    descDe: "Alle A1-Grammatik kombinieren und bereit für A2 sein.",
    descAr: "جمع كل قواعد A1 في جمل صحيحة، مراجعة شاملة، والاستعداد لامتحان الختم وA2.",
    lessons: 1,
    minutes: 35,
    keyWords: ["die Wiederholung", "kombinieren", "die Prüfung", "bereit für A2"],
  },

  // ═══ A2 — 12 وحدة ═══
  {
    id: "a2-01",
    level: "A2",
    number: 1,
    titleDe: "Reisen und Urlaub",
    titleAr: "السفر والعطلات",
    descDe: "Urlaubserlebnisse im Perfekt erzählen.",
    descAr: "حكاية تجارب السفر بصيغة الماضي التام (Perfekt) مع haben/sein.",
    lessons: 6,
    minutes: 55,
    keyWords: ["der Urlaub", "die Reise", "das Perfekt", "sein/haben"],
  },
  {
    id: "a2-02",
    level: "A2",
    number: 2,
    titleDe: "Beim Arzt",
    titleAr: "الصحة والطبيب",
    descDe: "Körperteile, Krankheiten und Ratschläge.",
    descAr: "أجزاء الجسم، الأمراض، وطلب النصيحة مع (sollen/sollte).",
    lessons: 6,
    minutes: 55,
    keyWords: ["der Körper", "die Schmerzen", "der Termin", "sollen"],
  },
  {
    id: "a2-03",
    level: "A2",
    number: 3,
    titleDe: "Im Restaurant",
    titleAr: "المطعم والطعام",
    descDe: "Bestellen, bezahlen und über Geschmack sprechen.",
    descAr: "طلب الطعام، الدفع، والتعبير عن الرأي في الأكل (schmecken).",
    lessons: 6,
    minutes: 50,
    keyWords: ["die Speisekarte", "bestellen", "schmecken", "die Rechnung"],
  },
  {
    id: "a2-04",
    level: "A2",
    number: 4,
    titleDe: "Wohnungssuche",
    titleAr: "البحث عن سكن",
    descDe: "Anzeigen verstehen und eine Wohnung beschreiben.",
    descAr: "فهم إعلانات العقارات، وصف شقة، وحروف الجر المتغيرة (Wechselpräpositionen).",
    lessons: 6,
    minutes: 55,
    keyWords: ["die Wohnung", "die Miete", "der Vermieter", "Wechselpräpositionen"],
  },
  {
    id: "a2-05",
    level: "A2",
    number: 5,
    titleDe: "Im Büro",
    titleAr: "في المكتب والعمل",
    descDe: "Telefonieren, E-Mails schreiben und Termine koordinieren.",
    descAr: "الاتصالات الهاتفية، كتابة البريد الإلكتروني البسيط، وتنسيق المواعيد.",
    lessons: 6,
    minutes: 50,
    keyWords: ["das Büro", "anrufen", "die E-Mail", "der Kollege"],
  },
  {
    id: "a2-06",
    level: "A2",
    number: 6,
    titleDe: "Medien und Nachrichten",
    titleAr: "الإعلام والأخبار",
    descDe: "Über Medien sprechen und Nachrichten verstehen.",
    descAr: "التحدث عن وسائل الإعلام، فهم الأخبار، والرأي الشخصي (ich finde/ich glaube).",
    lessons: 5,
    minutes: 45,
    keyWords: ["das Fernsehen", "die Zeitung", "das Internet", "die Nachrichten"],
  },
  {
    id: "a2-07",
    level: "A2",
    number: 7,
    titleDe: "Bank und Geld",
    titleAr: "البنك والمال",
    descDe: "Bankgespräche, Geld und Zahlungsarten.",
    descAr: "معاملات البنك، المال، وطرق الدفع (überweisen/bar zahlen).",
    lessons: 5,
    minutes: 45,
    keyWords: ["das Konto", "das Geld", "überweisen", "bar"],
  },
  {
    id: "a2-08",
    level: "A2",
    number: 8,
    titleDe: "Mobil sein",
    titleAr: "المواصلات والتنقل",
    descDe: "Fahrkarten kaufen, Verbindungen und Verkehrsmittel.",
    descAr: "شراء التذاكر، جداول المواصلات، ووسائل النقل (Bahn/Bus/Straßenbahn).",
    lessons: 5,
    minutes: 45,
    keyWords: ["die Fahrkarte", "der Zug", "umsteigen", "die Haltestelle"],
  },
  {
    id: "a2-09",
    level: "A2",
    number: 9,
    titleDe: "Feste und Feiern",
    titleAr: "المناسبات والاحتفالات",
    descDe: "Einladungen, Geschenke und Feste in Deutschland.",
    descAr: "الدعوات، الهدايا، والمناسبات الألمانية (Geburtstag/Weihnachten...).",
    lessons: 5,
    minutes: 45,
    keyWords: ["die Einladung", "feiern", "das Geschenk", "der Geburtstag"],
  },
  {
    id: "a2-10",
    level: "A2",
    number: 10,
    titleDe: "Lernen und Schule",
    titleAr: "المدرسة والتعلم",
    descDe: "Über Lernen, Kurse und Prüfungen sprechen.",
    descAr: "الحديث عن الدراسة والدورات والامتحانات، والجمل الثانوية (dass/weil).",
    lessons: 5,
    minutes: 50,
    keyWords: ["der Kurs", "lernen", "die Prüfung", "weil", "dass"],
  },
  {
    id: "a2-11",
    level: "A2",
    number: 11,
    titleDe: "Dienstleistungen",
    titleAr: "الخدمات والمعاملات",
    descDe: "Post, Friseur, Reparaturen und Beschwerden.",
    descAr: "البريد، الحلاق، الإصلاحات، وتقديم شكوى بأدب.",
    lessons: 5,
    minutes: 45,
    keyWords: ["die Post", "der Friseur", "reparieren", "sich beschweren"],
  },
  {
    id: "a2-12",
    level: "A2",
    number: 12,
    titleDe: "Zwischenmenschliches",
    titleAr: "العلاقات بين الناس",
    descDe: "Gefühle, Meinungen und Konflikte ansprechen.",
    descAr: "المشاعر والآراء، الأفعال الانعكاسية، والتعامل مع الخلافات.",
    lessons: 5,
    minutes: 50,
    keyWords: ["die Gefühle", "die Meinung", "sich freuen", "sich ärgern"],
  },

  // ═══ B1 — 10 وحدات ═══
  {
    id: "b1-01",
    level: "B1",
    number: 1,
    titleDe: "Ausbildung und Studium",
    titleAr: "التعليم والدراسة",
    descDe: "Bildungssysteme vergleichen und Studiengänge beschreiben.",
    descAr: "مقارنة الأنظمة التعليمية، وصف التخصصات، وصيغ التفضيل والشرط (als ob/wenn).",
    lessons: 6,
    minutes: 60,
    keyWords: ["die Ausbildung", "das Studium", "der Studiengang", "der Vergleich"],
  },
  {
    id: "b1-02",
    level: "B1",
    number: 2,
    titleDe: "Arbeitswelt",
    titleAr: "عالم العمل",
    descDe: "Bewerbungen, Arbeitsbedingungen und Berufserfahrung.",
    descAr: "طلبات التوظيف، ظروف العمل، والخبرات المهنية بصيغة Präteritum.",
    lessons: 6,
    minutes: 60,
    keyWords: ["die Bewerbung", "der Arbeitgeber", "die Erfahrung", "das Präteritum"],
  },
  {
    id: "b1-03",
    level: "B1",
    number: 3,
    titleDe: "Umwelt und Klima",
    titleAr: "البيئة والمناخ",
    descDe: "Umweltprobleme diskutieren und Lösungen vorschlagen.",
    descAr: "مناقشة مشاكل البيئة، اقتراح الحلول، والمبني للمجهول (Passiv).",
    lessons: 6,
    minutes: 60,
    keyWords: ["die Umwelt", "das Klima", "der Müll", "das Passiv"],
  },
  {
    id: "b1-04",
    level: "B1",
    number: 4,
    titleDe: "Medien und Gesellschaft",
    titleAr: "الإعلام والمجتمع",
    descDe: "Medien kritisch betrachten und Meinungen begründen.",
    descAr: "النظر النقدي للإعلام، تبرير الآراء، والجمل السببية (weil/da).",
    lessons: 6,
    minutes: 55,
    keyWords: ["die Medien", "die Meinung", "begründen", "da/weil"],
  },
  {
    id: "b1-05",
    level: "B1",
    number: 5,
    titleDe: "Gesundheit und Prävention",
    titleAr: "الصحة والوقاية",
    descDe: "Gesund leben, Sport und Vorsorge.",
    descAr: "الحياة الصحية، الرياضة، والوقاية مع الروابط الشرطية (wenn/falls).",
    lessons: 6,
    minutes: 55,
    keyWords: ["die Gesundheit", "die Vorsorge", "der Sport", "wenn", "falls"],
  },
  {
    id: "b1-06",
    level: "B1",
    number: 6,
    titleDe: "Kultur und Kunst",
    titleAr: "الثقافة والفن",
    descDe: "Kunstwerke beschreiben und über Kultur sprechen.",
    descAr: "وصف الأعمال الفنية، الحديث عن الثقافة، والجمل النسبية (Relativsätze).",
    lessons: 6,
    minutes: 55,
    keyWords: ["die Kunst", "das Museum", "beschreiben", "Relativsatz"],
  },
  {
    id: "b1-07",
    level: "B1",
    number: 7,
    titleDe: "Politik und Gesellschaft",
    titleAr: "السياسة والمجتمع",
    descDe: "Politische Grundbegriffe und gesellschaftliche Themen.",
    descAr: "المفاهيم السياسية الأساسية، القضايا المجتمعية، وحروف الجر مع المضاف إليه (wegen/trotz/während).",
    lessons: 6,
    minutes: 60,
    keyWords: ["die Politik", "die Gesellschaft", "wegen", "trotz"],
  },
  {
    id: "b1-08",
    level: "B1",
    number: 8,
    titleDe: "Technik und Digitales",
    titleAr: "التقنية والرقمنة",
    descDe: "Technik im Alltag, Vor- und Nachteile abwägen.",
    descAr: "التقنية في الحياة اليومية، موازنة الإيجابيات والسلبيات (einerseits/andererseits).",
    lessons: 6,
    minutes: 55,
    keyWords: ["die Technik", "der Computer", "digital", "einerseits"],
  },
  {
    id: "b1-09",
    level: "B1",
    number: 9,
    titleDe: "Soziales Engagement",
    titleAr: "العمل التطوعي والاجتماعي",
    descDe: "Ehrenamt, Projekte und soziales Engagement.",
    descAr: "العمل التطوعي، المشاريع الاجتماعية، وصيغة المستقبل (Futur I).",
    lessons: 5,
    minutes: 50,
    keyWords: ["das Ehrenamt", "das Projekt", "helfen", "das Futur"],
  },
  {
    id: "b1-10",
    level: "B1",
    number: 10,
    titleDe: "Zukunft und Pläne",
    titleAr: "المستقبل والخطط",
    descDe: "Über Zukunftspläne sprechen und Vermutungen äußern.",
    descAr: "التحدث عن خطط المستقبل، التعبير عن الافتراضات بصيغة Konjunktiv II.",
    lessons: 5,
    minutes: 50,
    keyWords: ["die Zukunft", "der Plan", "würde", "könnte"],
  },
  /* ═══ المرحلة 4: وحدة b1-11 (المراجعة الختامية B1) — كانت مفقودة من المسار ═══ */
  {
    id: "b1-11",
    level: "B1",
    number: 11,
    titleDe: "B1 kompakt — Prüfungsvorbereitung",
    titleAr: "B1 الشامل — التحضير للامتحان",
    descDe: "Gesamtwiederholung von B1 und Prüfungsvorbereitung.",
    descAr: "المراجعة الختامية لمستوى B1 ودمج القواعد في مواقف حية، مع محاكاة أقسام Goethe-B1.",
    lessons: 1,
    minutes: 45,
    keyWords: ["Wiederholung", "Prüfung", "Mediation", "Interaktion"],
  },

  // ═══ B2 — 10 وحدات ═══
  {
    id: "b2-01",
    level: "B2",
    number: 1,
    titleDe: "Wissenschaft und Forschung",
    titleAr: "العلوم والبحث",
    descDe: "Wissenschaftliche Themen verstehen und referieren.",
    descAr: "فهم الموضوعات العلمية، تقديم عرض، ونقل الكلام غير المباشر (Konjunktiv I).",
    lessons: 6,
    minutes: 65,
    keyWords: ["die Wissenschaft", "die Forschung", "das Referat", "Konjunktiv I"],
  },
  {
    id: "b2-02",
    level: "B2",
    number: 2,
    titleDe: "Wirtschaft und Finanzen",
    titleAr: "الاقتصاد والمالية",
    descDe: "Wirtschaftsnachrichten und Marktentwicklungen analysieren.",
    descAr: "تحليل الأخبار الاقتصادية وتطورات الأسواق بمفردات متخصصة.",
    lessons: 6,
    minutes: 65,
    keyWords: ["die Wirtschaft", "der Markt", "die Konjunktur", "analysieren"],
  },
  {
    id: "b2-03",
    level: "B2",
    number: 3,
    titleDe: "Recht und Alltag",
    titleAr: "القانون والحياة اليومية",
    descDe: "Rechtliche Grundbegriffe und Verträge verstehen.",
    descAr: "المفاهيم القانونية الأساسية، فهم العقود، والصيغ الرسمية.",
    lessons: 6,
    minutes: 60,
    keyWords: ["das Recht", "der Vertrag", "das Gesetz", "formell"],
  },
  {
    id: "b2-04",
    level: "B2",
    number: 4,
    titleDe: "Literatur und Medien",
    titleAr: "الأدب والإعلام المتقدم",
    descDe: "Literarische Texte und anspruchsvolle Medienbeiträge.",
    descAr: "النصوص الأدبية والمساهمات الإعلامية الراقية، والصفات المشتقة من الفعل (Partizipien).",
    lessons: 6,
    minutes: 60,
    keyWords: ["die Literatur", "der Roman", "der Beitrag", "Partizip"],
  },
  {
    id: "b2-05",
    level: "B2",
    number: 5,
    titleDe: "Psychologie und Kommunikation",
    titleAr: "علم النفس والتواصل",
    descDe: "Kommunikationsmodelle und psychologische Aspekte.",
    descAr: "نماذج التواصل والجوانب النفسية، والافتراضات والتحفظات (es sei denn, je nachdem).",
    lessons: 6,
    minutes: 60,
    keyWords: ["die Psychologie", "die Kommunikation", "das Verhalten", "je nachdem"],
  },
  {
    id: "b2-06",
    level: "B2",
    number: 6,
    titleDe: "Beruf und Karriere",
    titleAr: "المسار المهني",
    descDe: "Karrierewege, Verhandlungen und professionelle Kommunikation.",
    descAr: "المسارات المهنية، التفاوض، والتواصل الاحترافي الرسمي.",
    lessons: 6,
    minutes: 60,
    keyWords: ["die Karriere", "verhandeln", "professionell", "die Führungskraft"],
  },
  {
    id: "b2-07",
    level: "B2",
    number: 7,
    titleDe: "Philosophie und Gesellschaft",
    titleAr: "الفلسفة والمجتمع",
    descDe: "Abstrakte Themen diskutieren und argumentieren.",
    descAr: "مناقشة الموضوعات المجردة، بناء الحجج، والكتابة الجدلية (Erörterung).",
    lessons: 6,
    minutes: 60,
    keyWords: ["die Philosophie", "argumentieren", "die These", "die Erörterung"],
  },
  {
    id: "b2-08",
    level: "B2",
    number: 8,
    titleDe: "Sprachen und Kulturen",
    titleAr: "اللغات والتبادل الثقافي",
    descDe: "Interkulturelle Unterschiede und Mehrsprachigkeit.",
    descAr: "الاختلافات بين الثقافات، تعدد اللغات، والاشتقاق الاسمي (Nominalisierung).",
    lessons: 6,
    minutes: 60,
    keyWords: ["die Kultur", "mehrsprachig", "interkulturell", "Nominalisierung"],
  },
  {
    id: "b2-09",
    level: "B2",
    number: 9,
    titleDe: "Arbeitsmarkt und Bewerbung",
    titleAr: "سوق العمل والتقديم الوظيفي",
    descDe: "Bewerbungsunterlagen und Vorstellungsgespräche führen.",
    descAr: "ملفات التقديم، مقابلات العمل، والمراسلات الرسمية الكاملة.",
    lessons: 6,
    minutes: 65,
    keyWords: ["der Lebenslauf", "das Vorstellungsgespräch", "das Anschreiben"],
  },
  {
    id: "b2-10",
    level: "B2",
    number: 10,
    titleDe: "Studium in Deutschland",
    titleAr: "الدراسة في ألمانيا",
    descDe: "Universitätssystem, Seminare und wissenschaftliches Schreiben.",
    descAr: "النظام الجامعي، الندوات، والكتابة الأكاديمية العلمية (Fachsprache).",
    lessons: 6,
    minutes: 65,
    keyWords: ["die Universität", "das Seminar", "die Fachsprache", "die Hausarbeit"],
  },
];

/** إرجاع وحدات مستوى معيّن مرتبة */
export function getUnitsByLevel(level: LevelMeta["code"]): Unit[] {
  return UNITS.filter((u) => u.level === level).sort((a, b) => a.number - b.number);
}

/** إجمالي عدد الوحدات في المنهج */
export const TOTAL_UNITS = UNITS.length;

/**
 * ═══ المرحلة 4 (توحيد الحقيقة): عدد الدروس يُشتق آلياً من LESSON_META ═══
 * (كان مجموعاً للقيم المعلنة الثابتة داخل UNITS = 251 — بينما الفعلية 48.
 *  الآن المصدر الوحيد للعدد هو الدروس الفعلية، فلا يمكن أن تختلف الأرقام بعد الآن)
 */
export const TOTAL_LESSONS = LESSON_META.length;

/** عدد الدروس الفعلية في وحدة معيّنة (يُحسب من LESSON_META — لا يُعلن يدوياً) */
export function getUnitLessonCount(unitId: string): number {
  return LESSON_META.filter((l) => l.unitId === unitId).length;
}

/** إجمالي الساعات الإرشادية الفعلية (من خريطة المنهج المطابقة للدروس) */
export const TOTAL_ESTIMATED_HOURS = 355;

/** الحصيلة المفرداتية الإجمالية التقريبية */
export const TOTAL_WORDS = LEVELS.reduce((sum, l) => sum + l.words, 0);
